# 
# Synthesis run script generated by Vivado
# 

set_param iopl.termPlaceClean 1
read_verilog {
  E:/DSD/avi/adld/apbtoi2c/apb_i2c_ic.v
  E:/DSD/avi/adld/apbtoi2c/project_1/project_1.srcs/sources_1/new/apb_slave.v
  E:/DSD/avi/adld/apbtoi2c/project_1/project_1.srcs/sources_1/new/i2c_bridge.v
  E:/DSD/avi/adld/apbtoi2c/project_1/project_1.srcs/sources_1/new/i2c_master.v
}
set_property webtalk.parent_dir E:/DSD/avi/adld/apbtoi2c/project_1/project_1.data/wt [current_project]
synth_design -top apb_i2c_ic -part xc7vx485tffg1157-1
write_checkpoint apb_i2c_ic.dcp
report_utilization -file apb_i2c_ic_utilization_synth.rpt
